import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "./components/ClientProvider";

export const metadata: Metadata = {
  title: "Dispatch hub",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
